name: Android CI

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build android app
        run: ./gradlew assembleDebug
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Build iOS shared code
        run: ./gradlew :composeApp:compileKotlinIosSimulatorArm64