name: WEB CI

# configure manual trigger
on: pull_request

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Build application
      - name: Build
        run: ./gradlew :composeApp:wasmJsBrowserDistribution
